services:
  _defaults:
    autowire: true
    autoconfigure: true

  Alchemy\AclBundle\Repository\DoctrinePermissionRepository: ~
  Alchemy\AclBundle\Security\PermissionManager: ~
  Alchemy\AclBundle\Mapping\ObjectMapping: ~
  Alchemy\AclBundle\Admin\PermissionView: ~
  Alchemy\AclBundle\Form\ObjectTypeFormType: ~
  Alchemy\AclBundle\Serializer\AceSerializer: ~
  Alchemy\AclBundle\Controller\PermissionController: ~

  Alchemy\AclBundle\Repository\PermissionRepositoryInterface: "@Alchemy\\AclBundle\\Repository\\DoctrinePermissionRepository"

  Alchemy\AclBundle\Security\Voter\AclVoter:
    tags:
      - { name: security.voter }

  Alchemy\AclBundle\Security\Voter\SetPermissionVoter:
    tags:
      - { name: security.voter }
