name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 7.4
        - 8.0
        - 8.1
        - 8.2
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: PHPUnit
        run: composer test
