name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 8.1
        - 8.2
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: xml, json, mbstring
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          rm -f composer.lock
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: PHPUnit
        run: composer test
